os: bionic
language: c
compiler: clang

before_install:
    - apt-get update; apt-get install -y clang-format-8 autotools-dev libtool
    - git clone https://github.com/openucx/ucx.git && cd ucx && ./autogen && ./configure --prefix=/usr && make -j4 install

script:
    - echo "TRAVIS_OS_NAME=$TRAVIS_OS_NAME"
    - ./autogen
    - ./configure
    - make
