os: linux
dist: xenial
language: cpp

language: java
jdk: oraclejdk9

jobs:
    include:
        - env: UCX_VERSION=master
          compiler: clang
#        - env: UCX_VERSION=v1.9.x
#          compiler: clang
#        - env: UCX_VERSION=v1.8.x
#          compiler: clang

before_install:
    - sudo apt-get update
    - sudo apt-get install -y clang-format-8 autotools-dev libtool libnuma-dev
    - java -version
    - git clone https://github.com/openucx/ucx.git
    - cd ucx
    - git checkout $UCX_VERSION
    - ./autogen.sh
    - ./configure --prefix=$HOME/usr --disable-gtest --disable-examples --with-java=no
    - make -j4 install
    - cd ..

script:
    - echo "TRAVIS_OS_NAME=$TRAVIS_OS_NAME"
    - pwd
    - ./autogen.sh
    - ./configure LDFLAGS="-L$HOME/usr/lib" CFLAGS="-I$HOME/usr/include"
    - make
